name: Check typos in PR
on: [ pull_request ]
jobs:
  build_pr:
    if: github.repository_owner == 'IntellectualSites'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check typos
        run: make typos
