name: Check for typos
on: [ pull_request ]
jobs:
  build_pr:
    if: github.repository_owner == 'IntellectualSites'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Check typos
        run: make typos
